/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#1070e8",
        "tertiary-fixed-dim": "#fbbc09",
        "secondary": "#0058bc",
        "on-tertiary-container": "#d09b00",
        "on-primary": "#ffffff",
        "on-primary-container": "#7fa1f2",
        "tertiary": "#302100",
        "on-surface-variant": "#434651",
        "inverse-surface": "#2d3133",
        "on-primary-fixed": "#001945",
        "surface-white": "#FFFFFF",
        "inverse-primary": "#b0c6ff",
        "on-primary-fixed-variant": "#1a438e",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-high": "#e6e8eb",
        "success": "#008009",
        "on-secondary-fixed": "#001a41",
        "surface-variant": "#e0e3e6",
        "rating-gold": "#FABB05",
        "on-secondary-container": "#fefcff",
        "error": "#D4111E",
        "outline-variant": "#c4c6d3",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eff1f4",
        "primary-fixed-dim": "#b0c6ff",
        "text-main": "#1A1A1A",
        "surface-bright": "#f7f9fc",
        "tertiary-container": "#4b3600",
        "on-tertiary-fixed": "#261a00",
        "primary-fixed": "#d9e2ff",
        "surface-container-highest": "#e0e3e6",
        "surface": "#f7f9fc",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fc",
        "on-error": "#ffffff",
        "primary": "#002155",
        "secondary-fixed": "#d8e2ff",
        "surface-dim": "#d8dadd",
        "primary-container": "#003580",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#004494",
        "surface-tint": "#375ca8",
        "outline": "#747782",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f7",
        "tertiary-fixed": "#ffdea0",
        "surface-container": "#eceef1",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#5c4300"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        sans: ["'Segoe UI'", "-apple-system", "BlinkMacSystemFont", "Roboto", "Arial", "sans-serif"],
        opensans: ["'Segoe UI'", "-apple-system", "BlinkMacSystemFont", "Roboto", "Arial", "sans-serif"],
        trivago: ["'Segoe UI'", "-apple-system", "BlinkMacSystemFont", "Roboto", "Arial", "sans-serif"],
        inter: ["'Segoe UI'", "-apple-system", "BlinkMacSystemFont", "Roboto", "Arial", "sans-serif"],
        jakarta: ["'Segoe UI'", "-apple-system", "BlinkMacSystemFont", "Roboto", "Arial", "sans-serif"],
        outfit: ["'Segoe UI'", "-apple-system", "BlinkMacSystemFont", "Roboto", "Arial", "sans-serif"],
        rubik: ["'Segoe UI'", "-apple-system", "BlinkMacSystemFont", "Roboto", "Arial", "sans-serif"]
      }
    },
  },
  plugins: [],
}
